import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'
import LoginBtn from './LoginBtn'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import { LogOutBtn } from './LogoutBtn'
import {cookies} from 'next/headers'
import DarkMode from './DarkMode'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {  
  let session = await getServerSession(authOptions)

  //let res = cookies().get('darkMode')
  //console.log(res)

  //useState('dark')

  return (
    <html lang="ko">
      <body className="">
        <div className="navbar">
          <div> 
            <Link href="/" className="logo">Appleforum</Link> 
            <Link href="/list">List</Link>
            { 
              session
                ? <span>{session.user.name} <LogOutBtn/> </span> 
                : <LoginBtn></LoginBtn>
            }
            
          </div>  
          <DarkMode/>          
        </div>
        { children }
      </body>
    </html>
  ) 
}
